/**
 * Audio Utilities for dB and Volume Conversion
 * 
 * Key concepts:
 * - 10 dB increase = 10x sound pressure level (perceived as ~2x louder)
 * - 6 dB increase = doubles amplitude (2x voltage)
 * - 3 dB increase = doubles power (2x energy)
 * 
 * Howler.js uses linear volume 0.0 to 1.0 (can go above 1.0 with Web Audio API)
 * We use -60 dB to +10 dB range in UI (-∞ to 0 dB in Howler, with +10dB headroom)
 */

/**
 * Convert decibels to linear volume
 * Formula: linear = 10^(dB/20)
 * 
 * @param db - Volume in decibels (-60 to +10)
 * @returns Linear volume (0.0 to ~3.16)
 */
export function dbToLinear(db: number): number {
  if (db <= -60) return 0;
  return Math.pow(10, db / 20);
}

/**
 * Convert linear volume to decibels
 * Formula: dB = 20 * log10(linear)
 * 
 * @param linear - Linear volume (0.0 to ~3.16)
 * @returns Volume in decibels (-60 to +10)
 */
export function linearToDb(linear: number): number {
  if (linear <= 0) return -60;
  return 20 * Math.log10(linear);
}

/**
 * Estimate audio level at current playback position
 * Combines volume setting with waveform data
 *
 * @param volume - Base volume (linear)
 * @param waveformValue - Waveform peak at current position (0-1)
 * @returns Current level in dB (-60 to +10)
 */
export function estimateCurrentLevel(volume: number, waveformValue: number): number {
  if (volume <= 0 || waveformValue <= 0) return -60;

  // Convert both to dB and add
  const volumeDb = linearToDb(volume);
  const waveformDb = linearToDb(waveformValue);
  const totalDb = volumeDb + waveformDb;

  return Math.max(-60, Math.min(10, totalDb));
}

// ---------------------------------------------------------------------------
// Server waveform → client WaveformData
// ---------------------------------------------------------------------------

/** One channel of a server waveform payload (see ServerWaveformChannel). */
export interface ServerChannelPeaks { peak?: number[]; rms?: number[] }

export interface MeasuredLoudness {
  analysis_version?: 1;
  integrated_lufs?: number | null;
  true_peak_dbtp?: number | null;
}

export interface BuiltWaveform {
  peaks: number[];
  length: number;
  duration: number;
  channelPeaks?: number[][];
  analysis_version?: 1;
  integrated_lufs?: number | null;
  true_peak_dbtp?: number | null;
}

/**
 * Build the client-side waveform record from the server's per-channel payload.
 *
 * The server measures every source channel independently. Taking `channels[0]`
 * — as every call site used to — threw away everything but the LEFT channel, so
 * a stereo file was drawn and analysed from half its audio (#47). We keep the
 * per-channel traces AND a combined trace (per-bucket max across channels) for
 * the compact renderers and for loudness/trim analysis.
 *
 * Returns null when the payload carries no usable buckets.
 */
export function buildWaveformFromChannels(
  channels: ServerChannelPeaks[] | undefined | null,
  durationSeconds: number,
  analysis?: MeasuredLoudness | null,
): BuiltWaveform | null {
  const lanes = (channels ?? [])
    .map(c => c?.peak)
    .filter((p): p is number[] => Array.isArray(p) && p.length > 0);
  if (lanes.length === 0) return null;

  const buckets = Math.max(...lanes.map(l => l.length));
  const peaks = new Array<number>(buckets).fill(0);
  for (const lane of lanes) {
    for (let i = 0; i < lane.length; i++) {
      const v = lane[i] ?? 0;
      if (v > peaks[i]!) peaks[i] = v;
    }
  }

  return {
    peaks,
    length: peaks.length,
    duration: durationSeconds,
    // Only worth carrying when there's more than one channel to show.
    ...(lanes.length > 1 ? { channelPeaks: lanes } : {}),
    ...(analysis?.analysis_version === 1 ? {
      analysis_version: 1 as const,
      integrated_lufs: Number.isFinite(analysis.integrated_lufs)
        ? analysis.integrated_lufs as number
        : null,
      true_peak_dbtp: Number.isFinite(analysis.true_peak_dbtp)
        ? analysis.true_peak_dbtp as number
        : null,
    } : {}),
  };
}

/**
 * Parse a cached waveform JSON file into a WaveformData record.
 *
 * Two schemas exist on disk:
 *   * the server's waveform cache — { channels: [{peak, rms}], duration_ms, … }
 *   * the legacy Electron/ffmpeg file — { peaks, duration, sampleRate }
 * Accept both, so a project whose waveforms were generated by the server isn't
 * needlessly regenerated by the Electron client (and keeps its channels).
 *
 * Returns null when the file carries no usable buckets.
 */
export function parseWaveformFileData(data: any): BuiltWaveform | null {
  if (!data || typeof data !== 'object') return null;

  if (Array.isArray(data.channels)) {
    const duration = typeof data.duration === 'number'
      ? data.duration
      : (data.duration_ms ?? 0) / 1000;
    return buildWaveformFromChannels(data.channels, duration, data);
  }

  if (Array.isArray(data.peaks) && data.peaks.length > 0) {
    return {
      peaks: data.peaks,
      length: data.peaks.length,
      duration: typeof data.duration === 'number' ? data.duration : 0,
      ...(Array.isArray(data.channelPeaks) && data.channelPeaks.length > 1
        ? { channelPeaks: data.channelPeaks }
        : {}),
      ...(data.analysis_version === 1 ? {
        analysis_version: 1 as const,
        integrated_lufs: Number.isFinite(data.integrated_lufs)
          ? data.integrated_lufs
          : null,
        true_peak_dbtp: Number.isFinite(data.true_peak_dbtp)
          ? data.true_peak_dbtp
          : null,
      } : {}),
    };
  }

  return null;
}

// ---------------------------------------------------------------------------
// Import processing. Trimming and loudness matching are independent opt-ins:
// callers decide which operation to run and which measured range to use.
// ---------------------------------------------------------------------------

interface ProcessableItem {
  duration: number;
  inPoint: number;
  outPoint: number;
  volume: number;
  waveform?: BuiltWaveform;
}

/**
 * Trim leading/trailing silence in-place. This never changes item volume.
 */
export function trimSilence(item: ProcessableItem): boolean {
  if (!item.waveform || !item.waveform.peaks || item.waveform.peaks.length === 0) return false;

  const peaks = item.waveform.peaks;
  const duration = item.duration || item.waveform.duration || 0;
  if (duration <= 0) return false;

  const maxPeak = peaks.reduce((m, v) => (v > m ? v : m), 0);
  if (maxPeak <= 0) return false;

  const threshold = maxPeak * 0.05;
  const padding = 0.1;
  let startIdx = peaks.findIndex(peak => peak > threshold);
  if (startIdx < 0) return false;
  let endIdx = peaks.length - 1;
  while (endIdx > startIdx && peaks[endIdx] <= threshold) endIdx--;

  const newInPoint = Math.max(0, (startIdx / peaks.length) * duration - padding);
  const newOutPoint = Math.min(duration, ((endIdx + 1) / peaks.length) * duration + padding);
  if (Math.abs(newInPoint - item.inPoint) <= 0.05 &&
      Math.abs(newOutPoint - item.outPoint) <= 0.05) {
    return false;
  }

  item.inPoint = newInPoint;
  item.outPoint = newOutPoint;
  return true;
}

/**
 * Return the absolute source gain needed for the measured range. Invalid
 * analysis and silence are intentionally no-ops.
 */
export function loudnessMatchedVolume(
  analysis: MeasuredLoudness | null | undefined,
  loudnessTargetLufs: number,
  limiterCeilingDb: number,
): number | null {
  if (analysis?.analysis_version !== 1 ||
      !Number.isFinite(analysis.integrated_lufs) ||
      !Number.isFinite(analysis.true_peak_dbtp) ||
      !Number.isFinite(loudnessTargetLufs) ||
      !Number.isFinite(limiterCeilingDb)) {
    return null;
  }

  const gainDb = Math.max(-60, Math.min(
    10,
    loudnessTargetLufs - (analysis.integrated_lufs as number),
    limiterCeilingDb - (analysis.true_peak_dbtp as number),
  ));
  return Math.pow(10, gainDb / 20);
}

/**
 * Apply an absolute, idempotent loudness match. This never changes trim points.
 */
export function applyLoudnessMatch(
  item: Pick<ProcessableItem, 'volume'>,
  analysis: MeasuredLoudness | null | undefined,
  loudnessTargetLufs: number,
  limiterCeilingDb: number,
): boolean {
  const volume = loudnessMatchedVolume(analysis, loudnessTargetLufs, limiterCeilingDb);
  if (volume === null || Math.abs(volume - item.volume) <= 0.000001) return false;
  item.volume = volume;
  return true;
}

export function exceedsTruePeakCeiling(
  item: Pick<ProcessableItem, 'duration' | 'inPoint' | 'outPoint' | 'volume'> &
    { waveform?: MeasuredLoudness & { duration?: number } },
  limiterCeilingDb: number,
): boolean {
  // Whole-file analysis cannot truthfully warn about a trimmed cue: the peak
  // may be outside the played range. Ranged analysis is fetched on demand by
  // Normalize; suppress this conservative row warning until we persist range
  // provenance with the waveform.
  const duration = item.duration || item.waveform?.duration || 0;
  const outPoint = item.outPoint > 0 ? item.outPoint : duration;
  if (duration > 0 && (item.inPoint > 0.001 || outPoint < duration - 0.001)) {
    return false;
  }

  const truePeak = item.waveform?.analysis_version === 1
    ? item.waveform.true_peak_dbtp
    : null;
  if (!Number.isFinite(truePeak) || !Number.isFinite(item.volume) ||
      item.volume <= 0 || !Number.isFinite(limiterCeilingDb)) {
    return false;
  }
  return (truePeak as number) + 20 * Math.log10(item.volume) > limiterCeilingDb;
}
